# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sec.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_second_window(object):
    def setupUi(self, second_window):
        second_window.setObjectName("second_window")
        second_window.resize(1200, 654)
        second_window.setAutoFillBackground(False)
        second_window.setStyleSheet("background-image: url(:/newPrefix/2.png);")
        second_window.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        second_window.setDocumentMode(False)
        second_window.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(second_window)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(820, 220, 201, 41))
        self.comboBox.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-image: url(:/newPrefix/1.JPG);\n"
"color: rgb(0, 170, 255);\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(570, 210, 211, 51))
        self.label.setStyleSheet("background-image: url(:/newPrefix/1.JPG);\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(950, 490, 201, 61))
        self.pushButton.setStyleSheet("background-image: url(:/newPrefix/1.JPG);\n"
"font: 75 22pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 255);\n"
" border-radius: 25px;\n"
"border: 3px solid #00AAFF;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 490, 201, 61))
        self.pushButton_2.setStyleSheet("background-image: url(:/newPrefix/1.JPG);\n"
"font: 75 22pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 255);\n"
" border-radius: 25px;\n"
"border: 3px solid #00AAFF;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(820, 320, 201, 41))
        self.comboBox_2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-image: url(:/newPrefix/1.JPG);\n"
"color: rgb(0, 170, 255);\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(570, 310, 211, 51))
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/1.JPG);\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(790, 70, 101, 51))
        self.label_2.setStyleSheet("background-image: url(:/newPrefix/1.JPG);\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 255);\n"
"")
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(740, 550, 201, 61))
        self.pushButton_3.setStyleSheet("background-image: url(:/newPrefix/1.JPG);\n"
"font: 75 22pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 255);\n"
" border-radius: 25px;\n"
"border: 3px solid #00AAFF;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(730, 440, 201, 61))
        self.pushButton_4.setStyleSheet("background-image: url(:/newPrefix/1.JPG);\n"
"font: 75 22pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 255);\n"
" border-radius: 25px;\n"
"border: 3px solid #00AAFF;")
        self.pushButton_4.setObjectName("pushButton_4")
        second_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(second_window)
        QtCore.QMetaObject.connectSlotsByName(second_window)

    def retranslateUi(self, second_window):
        _translate = QtCore.QCoreApplication.translate
        second_window.setWindowTitle(_translate("second_window", "Diagram"))
        self.comboBox.setItemText(0, _translate("second_window", "Device 1"))
        self.comboBox.setItemText(1, _translate("second_window", "Device 2"))
        self.label.setText(_translate("second_window", "Select Device  :"))
        self.pushButton.setText(_translate("second_window", "Show"))
        self.pushButton_2.setText(_translate("second_window", "Export"))
        self.comboBox_2.setItemText(0, _translate("second_window", "Day"))
        self.comboBox_2.setItemText(1, _translate("second_window", "Month"))
        self.comboBox_2.setItemText(2, _translate("second_window", "Year"))
        self.label_3.setText(_translate("second_window", "Select Date     :"))
        self.label_2.setText(_translate("second_window", "Govee"))
        self.pushButton_3.setText(_translate("second_window", "Alarms"))
        self.pushButton_4.setText(_translate("second_window", "Status"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    second_window = QtWidgets.QMainWindow()
    ui = Ui_second_window()
    ui.setupUi(second_window)
    second_window.show()
    sys.exit(app.exec_())
